### PR TITLE
Update the build script and add CMake-related files

### PR DESCRIPTION
**Pull request by giordano**
***Update**: this should now be working thanks to @staticfloat*

---

build for OS X is failing at linking stage with error:
```
clang-6.0: warning: argument unused during compilation: '-dynamiclib' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-install_name @rpath/libcspice.dylib' [-Wunused-command-line-argument]
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/lib/crt1.o: file not recognized: File format not recognized
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/cspice.dir/build.make:32320: libcspice.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/cspice.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
ERROR: LoadError: Build for cspice on x86_64-apple-darwin14 did not complete successfully
```
I have no idea why, I'll try to investigate.  Anyway, I'm opening the PR not to forget to come back on this (or if anyone else wants to fix this :smile: )

### CODE REVIEW

**Comment by staticfloat** [comment]
Can you run a build with `VERBOSE=1`?  This kind of error is often because the `-target` flags are not being passed to `clang` properly, so it starts emitting `x86_64-linux-gnu` code instead of `x86_64-apple-darwin14`, like it should.

**Comment by helgee** [comment]
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/cspice.dir/link.txt --verbose=1
/opt/x86_64-linux-gnu/tools/clang --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -O2 -DNON_UNIX_STDIO -dynamiclib -Wl,-headerpad_max_install_names -mmacosx-version-min=10.8 -Wl,-syslibroot,/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -o libcspice.dylib -install_name @rpath/libcspice.dylib @CMakeFiles/cspice.dir/objects1.rsp -lm 
clang-6.0: warning: argument unused during compilation: '-dynamiclib' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-install_name @rpath/libcspice.dylib' [-Wunused-command-line-argument]
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/lib/crt1.o: file not recognized: File format not recognized
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by staticfloat** [comment]
Fix here: https://github.com/giordano/SPICEBuilder/pull/1 and confirmed that it builds for all the platforms you've defined.  :)

**Comment by helgee** [comment]
Good catch @staticfloat 😊

**Pull request merged**
